# Training Classifier with the DRS_non_learnable_pretrain_false, lr=0.01

C1=6
C2=7
CASE=210825_DRS_nl_r50_c2

CUDA_VISIBLE_DEVICES=${C1},${C2} python scripts/train_cls.py \
    --img_dir=/data_root/WSSS/DRS_log/${CASE}/ \
    --lr=0.001 \
    --epoch=60 \
    --decay_points='20,40' \
    --delta=0.55 \
    --logdir=logs/${CASE} \
    --save_folder=checkpoints/${CASE} \
    --model=resnet50 \
    --show_interval=50

# Evaluation pseudo segmentation labels generated by the classifier
 CUDA_VISIBLE_DEVICES=${C1} python scripts/test_cls.py \
     --checkpoint=checkpoints/${CASE}/best.pth \
     --img_dir=/data_root/WSSS/DRS_log/${CASE}/ --delta=0.55 --model=resnet50


# Generating localization maps for the refinement learning
CUDA_VISIBLE_DEVICES=${C1} python scripts/localization_map_gen.py \
    --img_dir=/data_root/WSSS/DRS_log/${CASE}/ \
    --checkpoint=checkpoints/${CASE}/best.pth \
    --delta=0.55 --model=resnet50


# Refinement learning
CUDA_VISIBLE_DEVICES=${C1},${C2} python scripts/train_refine.py \
    --img_dir=/data_root/WSSS/DRS_log/${CASE}/ \
    --lr=0.0001 \
    --epoch=120 \
    --decay_points='40,80' \
    --logdir=logs/Refine_${CASE} \
    --save_folder=checkpoints/Refine_${CASE} \
    --show_interval=50 \
     --model=resnet50


# Evaluation pseudo segmentation labels generated by the refinement newtork
CUDA_VISIBLE_DEVICES=${C1} python scripts/test_refine.py \
    --checkpoint=checkpoints/Refine_${CASE}/best.pth --img_dir=/data_root/WSSS/DRS_log/${CASE}/ --model=resnet50

rm -rf /data_root/WSSS/DRS_log/${CASE}/localization_maps


# Pseudo segmentation label generation
CUDA_VISIBLE_DEVICES=${C1} python scripts/pseudo_seg_label_gen.py \
    --img_dir=/data_root/WSSS/DRS_log/${CASE}/ \
    --checkpoint=checkpoints/Refine_${CASE}/best.pth \
    --model=resnet50

