IMG_DIR_NAME=/dataset/WSSS/DRS_log/DRS_NL_CAAS1/
LOG_DIR_NAME=DRS_NL_CAAS1
C1=2
C2=3

# Training Classifier with DRS-CAAS
CUDA_VISIBLE_DEVICES=${C1},${C2} python scripts/train_cls.py \
    --img_dir=${IMG_DIR_NAME} \
    --lr=0.001 \
     --epoch=15 \
    --decay_points='5,10' \
    --delta=0.55 \
    --logdir=logs/${LOG_DIR_NAME} \
    --save_folder=checkpoints/${LOG_DIR_NAME} \
    --show_interval=50 \
    --loss_cls_aware_mode='cls_aware' \
    --lambda_cls=1. \
    --lambda_cls_aware=1.

# Evaluation pseudo segmentation labels generated by the classifier
 CUDA_VISIBLE_DEVICES=${C1} python scripts/test_cls.py \
     --checkpoint=checkpoints/${LOG_DIR_NAME}/best.pth \
     --img_dir=${IMG_DIR_NAME} \
     --delta=0.55


# Generating localization maps for the refinement learning
CUDA_VISIBLE_DEVICES=${C1} python scripts/localization_map_gen.py \
    --img_dir=${IMG_DIR_NAME} \
    --checkpoint=checkpoints/${LOG_DIR_NAME}/best.pth \
    --delta=0.55


# Refinement learning
CUDA_VISIBLE_DEVICES=${C1},${C2} python scripts/train_refine.py \
    --img_dir=${IMG_DIR_NAME} \
    --lr=0.0001 \
    --epoch=30 \
    --decay_points='10,20' \
    --logdir=logs/Refine_${LOG_DIR_NAME} \
    --save_folder=checkpoints/Refine_${LOG_DIR_NAME} \
    --show_interval=50


# Evaluation pseudo segmentation labels generated by the refinement network
 CUDA_VISIBLE_DEVICES=${C1} python scripts/test_refine.py \
    --checkpoint=checkpoints/Refine_${LOG_DIR_NAME}/best.pth \
    --img_dir=${IMG_DIR_NAME}


# Pseudo segmentation label generation
CUDA_VISIBLE_DEVICES=${C1} python scripts/pseudo_seg_label_gen.py \
    --img_dir=${IMG_DIR_NAME} \
    --checkpoint=checkpoints/Refine_${LOG_DIR_NAME}/best.pth




